#!/usr/bin/env python3
"""Regenerate test-vectors/network-identities.json from deterministic seeds.

Run from repo root:
    python test-vectors/generate_network_identity_vectors.py
"""

import hashlib
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey  # noqa: E402

from chainbreaker.crypto import encode_private_key, encode_public_key  # noqa: E402
from chainbreaker.network_identity import (  # noqa: E402
    alpha_network_identity,
    derive_network_identity,
)
from chainbreaker.registry_state import RegistryState, serialize_registry_state  # noqa: E402

VECTOR_SEEDS = [
    b"8md-vector-alpha-seed-0000000000",
    b"8md-vector-beta-seed--0000000001",
    b"8md-vector-gamma-seed-000000002",
]

WRONG_KEY_SEED = b"8md-vector-wrong-key-seed-0000003"


def _key_from_seed(seed: bytes) -> tuple[str, str]:
    sk = Ed25519PrivateKey.from_private_bytes(hashlib.sha256(seed).digest())
    pk = sk.public_key()
    return encode_private_key(sk), encode_public_key(pk)


def _derive_vector_keys():
    pairs = [_key_from_seed(s) for s in VECTOR_SEEDS]
    private_keys = [p[0] for p in pairs]
    public_keys = [p[1] for p in pairs]
    return private_keys, public_keys


def main() -> int:
    private_keys, public_keys = _derive_vector_keys()
    wrong_sk, wrong_pk = _key_from_seed(WRONG_KEY_SEED)

    base = derive_network_identity(
        network_id="chainbreaker-8md-test-vectors",
        governance_keys=public_keys,
        governance_threshold=2,
        kind="test",
        genesis_timestamp=1704067200,
        max_mining_iterations=10_000_000,
    )
    alpha = alpha_network_identity()

    base_root = base.genesis_registry_root
    wrong_root = base_root[:1] + ("1" if base_root[1] != "1" else "0") + base_root[2:]

    vector_doc = {
        "description": (
            "Protocol V2 network identity vectors for cross-implementation verification. "
            "Generated by Python; Rust must independently derive matching values."
        ),
        "vectors": [
            {
                "description": "alpha/legacy network identity (frozen)",
                "network_id": alpha.network_id,
                "kind": alpha.kind,
                "governance_keys": list(alpha.governance_keys),
                "governance_threshold": alpha.governance_threshold,
                "genesis_timestamp": alpha.genesis_timestamp,
                "expected_registry_root": alpha.genesis_registry_root,
                "expected_header_bytes_hex": alpha.genesis_header_bytes.hex(),
                "expected_header_hash": alpha.genesis_hash,
                "expected_registry_state_hex": serialize_registry_state(
                    RegistryState(
                        records=(),
                        governance_version=1,
                        network_id=alpha.network_id,
                        governance_keys=alpha.governance_keys,
                        threshold=alpha.governance_threshold,
                    )
                ).hex(),
            },
            {
                "description": "test network identity with vector-only governance keys",
                "network_id": base.network_id,
                "kind": base.kind,
                "governance_keys": list(base.governance_keys),
                "governance_threshold": base.governance_threshold,
                "genesis_timestamp": base.genesis_timestamp,
                "expected_registry_root": base.genesis_registry_root,
                "expected_header_bytes_hex": base.genesis_header_bytes.hex(),
                "expected_header_hash": base.genesis_hash,
                "expected_registry_state_hex": serialize_registry_state(
                    RegistryState(
                        records=(),
                        governance_version=1,
                        network_id=base.network_id,
                        governance_keys=base.governance_keys,
                        threshold=base.governance_threshold,
                    )
                ).hex(),
                "private_keys_hex": private_keys,
            },
        ],
        "negative_vectors": [
            {
                "description": "wrong network_id changes registry root and genesis hash",
                "variant": "wrong_network_id",
                "network_id": "chainbreaker-8md-test-vectors-wrong",
                "governance_keys": public_keys,
                "governance_threshold": 2,
                "genesis_timestamp": 1704067200,
                "expected_different_header_hash": True,
            },
            {
                "description": "wrong governance key changes registry root and genesis hash",
                "variant": "wrong_governance_key",
                "network_id": base.network_id,
                "governance_keys": [wrong_pk, public_keys[1], public_keys[2]],
                "governance_threshold": 2,
                "genesis_timestamp": base.genesis_timestamp,
                "expected_different_header_hash": True,
            },
            {
                "description": "wrong threshold changes registry root and genesis hash",
                "variant": "wrong_threshold",
                "network_id": base.network_id,
                "governance_keys": public_keys,
                "governance_threshold": 1,
                "genesis_timestamp": base.genesis_timestamp,
                "expected_different_header_hash": True,
            },
            {
                "description": (
                    "wrong genesis registry root mismatches independently derived header"
                ),
                "variant": "wrong_genesis_root",
                "network_id": base.network_id,
                "governance_keys": public_keys,
                "governance_threshold": 2,
                "genesis_timestamp": base.genesis_timestamp,
                "tampered_registry_root": wrong_root,
                "expected_validity": False,
            },
        ],
    }

    vectors_dir = REPO / "test-vectors"
    vectors_dir.mkdir(parents=True, exist_ok=True)
    (vectors_dir / "network-identities.json").write_text(
        json.dumps(vector_doc, indent=2), encoding="utf-8"
    )
    (vectors_dir / "network-identities-test-genesis.bin").write_bytes(base.genesis_header_bytes)
    (vectors_dir / "network-identities-test-genesis.hash").write_text(
        base.genesis_hash + "\n", encoding="utf-8"
    )

    print(f"Regenerated {vectors_dir / 'network-identities.json'}")
    print(f"Regenerated {vectors_dir / 'network-identities-test-genesis.bin'}")
    print(f"Regenerated {vectors_dir / 'network-identities-test-genesis.hash'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
