# CONSENSUS-CRITICAL: Protocol V2 consensus-sensitive code. Changes require review per docs/CONSENSUS_CHANGE_POLICY.md.

"""Block structure, proof-of-work, and validation with 256-bit target."""

from __future__ import annotations

import copy
import time
from dataclasses import dataclass
from typing import Any, Callable

from .codec import BinaryCodec, validate_v2_transaction
from .crypto import HashEngine, MerkleTree, hex_to_target, target_to_hex

PROTOCOL_VERSION = 2
NETWORK_ID = "chainbreaker-scripture-v2"
GENESIS_MESSAGE = "Chain-Breaker v2 Genesis: ledger-derived curator governance"
GENESIS_TIMESTAMP = 1704067200

# Bitcoin-style maximum target
MAX_TARGET = 0x0000FFFF00000000000000000000000000000000000000000000000000000000
MIN_TARGET = 0x0000000000000000000000000000000000000000000000000000000000000001

# Genesis target: easy enough to mine quickly, but bounded.
GENESIS_TARGET = MAX_TARGET
GENESIS_TARGET_HEX = "0000ffff00000000000000000000000000000000000000000000000000000000"

# Genesis governance keys and threshold (protocol constants).
# These placeholder keys are not valid Ed25519 curve points; a production
# network must replace them with keys generated by an independent ceremony.
GENESIS_GOVERNANCE_KEYS = [
    "0000000000000000000000000000000000000000000000000000000000000000",
    "1111111111111111111111111111111111111111111111111111111111111111",
    "2222222222222222222222222222222222222222222222222222222222222222",
]
GENESIS_THRESHOLD = 2

# Hard-coded v2 genesis constants.  These are the canonical values for the
# chainbreaker-scripture-v2 network and must not change.
GENESIS_NONCE = 42129
GENESIS_HASH = "0000a6fd1e57aafd19da552440faa94803dbf1a1773bcd9af8ce3e0ae9fd13db"
GENESIS_REGISTRY_ROOT = "5814321ad489e630fef0350b1bff591d5cee8a821c00fa40a2cb2c99bd5b3186"
GENESIS_HEADER_BYTES = bytes.fromhex("0202000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005814321ad489e630fef0350b1bff591d5cee8a821c00fa40a2cb2c99bd5b318680009265000000000000ffff0000000000000000000000000000000000000000000000000000000091a4000000000000")

def header_bytes(header: dict[str, Any]) -> bytes:
    """Canonical serialization of a block header."""
    return BinaryCodec.encode_header(header)


def mine_header_v2(header: BlockHeaderV2,
                              max_iterations: int = 10_000_000,
                              start_nonce: int = 0) -> bool:
    """Deterministic v2 proof-of-work search.

    Mutates `header.nonce` in place until `header.hash()` satisfies
    `header.target` or `max_iterations` is reached.  The nonce wraps modulo
    2**64 on exhaustion.
    """
    if header.prev_hash == "0" * 64 and header.version == PROTOCOL_VERSION:
        # Refuse to re-mine the fixed genesis header.
        pass
    for _ in range(max_iterations):
        if satisfies_pow(header.hash(), header.target):
            return True
        header.nonce = (header.nonce + 1) & 0xFFFFFFFFFFFFFFFF
    return False


def header_hash(header: dict[str, Any]) -> str:
    """Double-SHA256 of the canonical header bytes."""
    return HashEngine.hash_double_hex(header_bytes(header))


def header_v2_hash(header: dict[str, Any]) -> str:
    """Double-SHA256 of the canonical v2 header bytes."""
    return HashEngine.hash_double_hex(BinaryCodec.encode_header_v2(header))


def satisfies_pow(block_hash: str, target: int) -> bool:
    """Check whether a 64-char hex block hash meets the target."""
    return int(block_hash, 16) <= target


def verify_genesis(header_bytes: bytes | None = None,
                   expected_hash: str | None = None,
                   expected_registry_root: str | None = None) -> bool:
    """Verify that a candidate genesis header matches the v2 constants.

    If no arguments are given, the function verifies the canonical constants
    against themselves.  Callers may provide bytes from the network to
    confirm they match the protocol genesis.
    """
    if header_bytes is None:
        header_bytes = GENESIS_HEADER_BYTES
    if len(header_bytes) != 149:
        return False

    try:
        header, _ = BinaryCodec.decode_header_v2(header_bytes)
    except Exception:
        return False

    if header["version"] != 2:
        return False
    if header["prev_hash"] != "0" * 64:
        return False
    if header["merkle_root"] != "0" * 64:
        return False
    if header["timestamp"] != GENESIS_TIMESTAMP:
        return False
    if header["target"] != GENESIS_TARGET_HEX:
        return False

    computed_hash = header_v2_hash(header)
    if expected_hash is None:
        expected_hash = GENESIS_HASH
    if computed_hash != expected_hash:
        return False

    if not satisfies_pow(computed_hash, GENESIS_TARGET):
        return False

    if expected_registry_root is None:
        expected_registry_root = GENESIS_REGISTRY_ROOT
    return bool(header["registry_root"] == expected_registry_root)


@dataclass
class BlockHeader:
    version: int
    prev_hash: str
    merkle_root: str
    timestamp: int  # Unix seconds
    target: int  # 256-bit integer
    nonce: int

    def to_dict(self) -> dict[str, Any]:
        return {
            "version": self.version,
            "prev_hash": self.prev_hash,
            "merkle_root": self.merkle_root,
            "timestamp": self.timestamp,
            "target": target_to_hex(self.target),
            "nonce": self.nonce,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> BlockHeader:
        return cls(
            version=int(data["version"]),
            prev_hash=str(data["prev_hash"]),
            merkle_root=str(data["merkle_root"]),
            timestamp=int(data["timestamp"]),
            target=hex_to_target(str(data["target"])),
            nonce=int(data["nonce"]),
        )

    def hash(self) -> str:
        return header_hash(self.to_dict())


@dataclass
class BlockHeaderV2:
    """Protocol v2 block header with registry-root commitment."""

    version: int
    prev_hash: str
    merkle_root: str
    registry_root: str
    timestamp: int  # Unix seconds
    target: int  # 256-bit integer
    nonce: int

    def to_dict(self) -> dict[str, Any]:
        return {
            "version": self.version,
            "prev_hash": self.prev_hash,
            "merkle_root": self.merkle_root,
            "registry_root": self.registry_root,
            "timestamp": self.timestamp,
            "target": target_to_hex(self.target),
            "nonce": self.nonce,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> BlockHeaderV2:
        return cls(
            version=int(data["version"]),
            prev_hash=str(data["prev_hash"]),
            merkle_root=str(data["merkle_root"]),
            registry_root=str(data["registry_root"]),
            timestamp=int(data["timestamp"]),
            target=hex_to_target(str(data["target"])),
            nonce=int(data["nonce"]),
        )

    def hash(self) -> str:
        return HashEngine.hash_double_hex(BinaryCodec.encode_header_v2(self.to_dict()))

    def mine(self, max_iterations: int = 10_000_000, start_nonce: int = 0) -> bool:
        """Find a nonce satisfying the v2 PoW target."""
        return mine_header_v2(self, max_iterations=max_iterations, start_nonce=start_nonce)


@dataclass
class Block:
    header: BlockHeader
    transactions: list[dict[str, Any]]

    def calculate_hash(self) -> str:
        return self.header.hash()

    @property
    def hash(self) -> str:
        return self.calculate_hash()

    def merkle_root(self) -> str:
        if not self.transactions:
            return "0" * 64
        tx_hashes = [HashEngine.hash_object(tx) for tx in self.transactions]
        root = MerkleTree(tx_hashes).root
        return HashEngine.hex(root) if root else "0" * 64

    def verify(self, *, reference_time: int | None = None,
               allow_genesis: bool = False,
               median_past: int | None = None,
               expected_target: int | None = None,
               transaction_validator: Callable[[dict[str, Any]], bool] | None = None) -> bool:
        """Verify block integrity."""
        # Target bounds
        if not (MIN_TARGET <= self.header.target <= MAX_TARGET):
            return False

        # Recompute Merkle root
        if self.merkle_root() != self.header.merkle_root:
            return False

        # Recompute and check PoW
        if not satisfies_pow(self.hash, self.header.target):
            return False

        if expected_target is not None and self.header.target != expected_target:
            return False

        if allow_genesis and self.is_genesis():
            return self._verify_genesis()

        # Future-timestamp bound
        now = reference_time or int(time.time())
        if self.header.timestamp > now + 7200:
            return False

        # Median-past rule
        if median_past is not None and self.header.timestamp <= median_past:
            return False

        # Validate transactions if a validator is supplied
        # Baseline V2 transaction schema validation is mandatory.
        for tx in self.transactions:
            try:
                validate_v2_transaction(tx)
            except Exception:
                return False

        if transaction_validator is not None:
            for tx in self.transactions:
                if not transaction_validator(tx):
                    return False

        return True

    def is_genesis(self) -> bool:
        return self.header.prev_hash == "0" * 64

    def _verify_genesis(self) -> bool:
        expected = create_genesis_block()
        return (
            self.header.version == expected.header.version
            and self.header.prev_hash == expected.header.prev_hash
            and self.header.timestamp == expected.header.timestamp
            and self.header.target == expected.header.target
            and self.header.nonce == expected.header.nonce
            and self.header.merkle_root == expected.header.merkle_root
            and self.transactions == expected.transactions
            and self.hash == expected.hash
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "header": self.header.to_dict(),
            "transactions": self.transactions,
            "hash": self.hash,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Block:
        header = BlockHeader.from_dict(data["header"])
        # Ignore any stored hash; recompute.
        return cls(header=header, transactions=list(data.get("transactions", [])))

    def mine(self, max_iterations: int = 10_000_000) -> bool:
        """Find a nonce satisfying the target."""
        for _ in range(max_iterations):
            if satisfies_pow(self.hash, self.header.target):
                return True
            self.header.nonce += 1
        return False


@dataclass
class BlockV2:
    """Protocol v2 block with registry-root commitment."""

    header: BlockHeaderV2
    transactions: list[dict[str, Any]]

    def calculate_hash(self) -> str:
        return self.header.hash()

    @property
    def hash(self) -> str:
        return self.calculate_hash()

    def merkle_root(self) -> str:
        if not self.transactions:
            return "0" * 64
        tx_hashes = [HashEngine.hash_object(tx) for tx in self.transactions]
        root = MerkleTree(tx_hashes).root
        return HashEngine.hex(root) if root else "0" * 64

    def to_dict(self) -> dict[str, Any]:
        return {
            "header": self.header.to_dict(),
            "transactions": copy.deepcopy(self.transactions),
            "hash": self.hash,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> BlockV2:
        header = BlockHeaderV2.from_dict(data["header"])
        return cls(header=header, transactions=list(data.get("transactions", [])))

    def mine(self, max_iterations: int = 10_000_000, start_nonce: int = 0) -> bool:
        """Find a nonce satisfying the v2 target."""
        return self.header.mine(max_iterations=max_iterations, start_nonce=start_nonce)

    def is_genesis(self) -> bool:
        return self.header.prev_hash == "0" * 64 and self.hash == GENESIS_HASH

    def verify(self, *, reference_time: int | None = None,
               allow_genesis: bool = False,
               median_past: int | None = None,
               expected_target: int | None = None,
               transaction_validator: Callable[[dict[str, Any]], bool] | None = None) -> bool:
        """Verify v2 block integrity.

        Generic V2 transaction schema validation is mandatory. The optional
        ``transaction_validator`` callback may apply additional
        application-specific checks, but it cannot disable the baseline
        consensus schema validation.
        """
        if self.header.version != PROTOCOL_VERSION:
            return False
        if allow_genesis and self.is_genesis():
            return True

        if not (MIN_TARGET <= self.header.target <= MAX_TARGET):
            return False

        if self.merkle_root() != self.header.merkle_root:
            return False

        if not satisfies_pow(self.hash, self.header.target):
            return False

        if expected_target is not None and self.header.target != expected_target:
            return False

        if self.header.timestamp <= 0:
            return False

        if reference_time is not None and self.header.timestamp > reference_time + 2 * 60 * 60:
            return False

        if median_past is not None and self.header.timestamp <= median_past:
            return False

        # Baseline V2 transaction schema validation is mandatory.
        for tx in self.transactions:
            try:
                validate_v2_transaction(tx)
            except Exception:
                return False

        if transaction_validator is not None:
            for tx in self.transactions:
                if not transaction_validator(tx):
                    return False

        return True


def _compute_genesis_constants() -> BlockV2:
    """Compute the canonical v2 genesis block once (used only by generator tools)."""
    genesis_tx = {
        "version": PROTOCOL_VERSION,
        "type": "genesis",
        "body": {
            "network_id": NETWORK_ID,
            "message": GENESIS_MESSAGE,
            "timestamp": GENESIS_TIMESTAMP,
        },
        "witnesses": [],
    }
    header = BlockHeaderV2(
        version=PROTOCOL_VERSION,
        prev_hash="0" * 64,
        merkle_root="0" * 64,
        registry_root=GENESIS_REGISTRY_ROOT,
        timestamp=GENESIS_TIMESTAMP,
        target=GENESIS_TARGET,
        nonce=0,
    )
    block = BlockV2(header=header, transactions=[genesis_tx])
    block.header.merkle_root = block.merkle_root()
    if not mine_header_v2(block.header):
        raise RuntimeError("failed to mine genesis block")
    return block


# _genesis_block is initialized lazily from the hard-coded genesis bytes.
_genesis_block: BlockV2 | None = None


def _build_genesis_block() -> BlockV2:
    """Build the canonical v2 genesis block from protocol constants."""
    header, _ = BinaryCodec.decode_header_v2(GENESIS_HEADER_BYTES)
    return BlockV2(header=BlockHeaderV2.from_dict(header), transactions=[])


def create_genesis_block(network_id: str | None = None) -> BlockV2:
    """Return the canonical v2 genesis block without re-mining."""
    global _genesis_block
    if _genesis_block is None:
        _genesis_block = _build_genesis_block()
    data = _genesis_block.to_dict()
    data["transactions"] = copy.deepcopy(data["transactions"])
    return BlockV2.from_dict(data)
